<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="MediatR" /> <!-- DO NOT UPDATE. Version 13+ requires a license. Plan to migrate to something else. -->
    <PackageReference Include="Crucible.Common.EntityEvents" />
  </ItemGroup>
</Project>
